# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Push to Docs

on:
  push:
    tags:
      - "effection-v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
          fetch-depth: 0 

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Get Version
        id: vars
        run: echo ::set-output name=version::$(echo ${{github.ref_name}} | sed 's/^effection-v//')

      - run: sed -i '/docs/d' .gitignore

      - name: Generate Docs
        run: deno doc --html --name=effection@$VERSION mod.ts
        env:
          VERSION: ${{steps.vars.outputs.version}}

      - run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .gitignore docs
          git commit -m "Add docs"
          git push --force origin tags/${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{github.token}}

      
      