name: Verify

on:
  push:
    branches: v[3-9]
  pull_request:
    branches: v[3-9]

permissions:
  contents: read

jobs:
  test-deno:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: format
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test
        run: deno task test

  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 22]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.com

      - name: test:node
        run: deno task test:node
