name: Verify

on:
  push:
    branches: v[3-9]
  pull_request:
    branches: v[3-9]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: format
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test (Windows)
        if: runner.os == 'Windows'
        run: deno task test
        shell: cmd

      - name: test (Unix)
        if: runner.os != 'Windows'
        run: deno task test

  jsr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: dry run publish
        run: deno publish --dry-run

  npm:
    needs: test-node
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # We use a totally dummy version and tag here
      # It could be anything. We're just verifying
      # that the package _could_ publish
      - name: Build
        run: deno task build:npm 4.0.0-verify.0

      - name: dry run publish
        run: npm publish --dry-run --tag=verify
        working-directory: ./build/npm

  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 22]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.com

      - name: test:node
        run: deno task test:node
