name: Verify

on:
  push:
    branches:
      - v[3-9]
  pull_request:
    branches:
      - v[3-9]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.com

      - name: format
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test (Windows)
        if: runner.os == 'Windows'
        run: deno test --allow-run --allow-write --allow-read --allow-env --allow-ffi --ignore=www
        shell: cmd

      - name: test (Unix)
        if: runner.os != 'Windows'
        run: deno task test

      - name: test:node
        run: deno task test:node
