name: Trigger Effection Website Rebuild

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  trigger-effection-rebuild:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: 1

    steps:
      - name: Trigger effection website rebuild
        env:
          GH_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        run: |
          gh workflow run www.yaml \
            --repo thefrontside/effection
